[package]
name = "maximumadhd/string-builder"
description = "StringBuilder - A module for printing formatted strings with an indent stack."
version = "1.0.0"
license = "MIT"
authors = ["MaximumADHD"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"