[package]
name = "maximumadhd/crunch-table"
description = "CrunchTable - A table compression library for Luau."
version = "1.0.2"
license = "MIT"
authors = ["MaximumADHD"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Guid = "maximumadhd/guid@1.0.1"
BufferExtras = "maximumadhd/buffer-extras@1.0.1"
