[package]
name = "maximumadhd/api-dump"
description = "ApiDump - Fetches and caches Roblox's API Dump with full type information and utility functions to interact with it."
version = "1.1.0"
license = "MIT"
authors = ["MaximumADHD"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"