[package]
name = "maximumadhd/network"
description = "Network - A super thin network library based on Red by jackdotink, with support for edit mode."
version = "1.1.0"
license = "MIT"
authors = ["MaximumADHD"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@^2"
RunContext = "maximumadhd/run-context@^1"