[package]
name = "maximumadhd/policy-info"
description = "PolicyInfo - A type-checked, promised version of Roblox's PolicyService."
version = "1.0.2"
license = "MIT"
authors = ["MaximumADHD"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "maximumadhd/promise-typed@1.0.0"