[package]
name = "maximumadhd/roblox-mesh"
description = "A parser for Roblox's ascii/binary mesh asset format."
version = "1.0.0"
license = "MIT"
authors = ["MaximumADHD"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
RunContext = "maximumadhd/run-context@1.0.1"