[package]
name = "maximumadhd/mutex"
description = "Mutex - A lightweight, attribute-controlled, mutual exclusion lock for instances"
version = "1.0.0"
license = "MIT"
authors = ["MaximumADHD"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"